services:
  abbot:
    image: ghcr.io/dhedegaard/abbot:main
    platform: linux/amd64
    environment:
      - USER=${USER}
      - PASSWORD=${PASSWORD}
    volumes:
      - output:/${OUTPUT_DIR}

volumes:
  output:
