services:
  abbot:
    # image: ghcr.io/dhedegaard/abbot:main
    build: .
    platform: linux/amd64
    environment:
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - OUTPUT_DIR=/output
    volumes:
      - output:/output

volumes:
  output:
